[programs.localnet]
minimal_mint = "3Numpd8aYKBbL9MVaFtqHxUotfpgqBGGMDiJZvkcHtwv"

[programs.devnet]
minimal_mint = "3Numpd8aYKBbL9MVaFtqHxUotfpgqBGGMDiJZvkcHtwv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/guilherme/my-solana-wallet/arceuus-keypair.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
